FROM apache/airflow:2.10.5-python3.11

COPY --chown=airflow:root ingestion/requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY --chown=airflow:root ingestion/ /opt/autointel/ingestion/
